const menuItems = document.querySelectorAll('.menu-item');
const views = document.querySelectorAll('.view');
const title = document.getElementById('page-title');
const sidebar = document.querySelector('.sidebar');
const toast = document.querySelector('.toast');
const modal = document.getElementById('modal-backdrop');
const modalContent = document.getElementById('modal-content');

const pageNames = { 'visao-geral': 'Visão geral', formacao: 'Minha formação', laboratorio: 'Laboratório', conexoes: 'Conexões', desempenho: 'Meu desempenho' };
const courseContent = {
  lesson: { eyebrow: 'MARKETING DIGITAL · AULA 06', title: 'Funil de vendas: da atenção à decisão', summary: 'Um funil organiza a jornada da pessoa: ela descobre uma solução, entende o valor e decide avançar. Seu trabalho é remover dúvidas em cada etapa.', objectives: ['Reconhecer atenção, consideração e decisão.', 'Relacionar conteúdo, anúncio e página ao momento certo.', 'Escolher uma métrica para cada etapa.'], steps: [['Atenção', 'Use conteúdo útil ou anúncio para mostrar um problema real.'], ['Consideração', 'Apresente prova, comparação, benefício e contexto.'], ['Decisão', 'Facilite a ação com oferta clara e um próximo passo único.']] },
  communication: { eyebrow: 'MÓDULO 01 · CONCLUÍDO', title: 'Comunicação', summary: 'Você concluiu a base de comunicação verbal, digital e apresentação pessoal. Esta competência acompanha todas as trilhas da Formação SkS.', objectives: ['Clareza na mensagem e adaptação ao público.', 'Estrutura de apresentação: contexto, proposta e próximo passo.', 'Postura profissional em reuniões, vídeos e atendimentos.'], steps: [['Pratique', 'Apresente uma solução em até 60 segundos.'], ['Revise', 'Corte termos técnicos que não ajudam seu público.'], ['Aplique', 'Peça uma devolutiva de quem assistiu.']] },
  ai: { eyebrow: 'MÓDULO 03 · PRÓXIMO', title: 'Inteligência Artificial', summary: 'Ferramentas de IA para pesquisa, criação, automação e produtividade, sempre com pensamento crítico e revisão humana.', objectives: ['Criar instruções claras para tarefas de marketing.', 'Usar IA para organizar ideias e hipóteses.', 'Avaliar fontes, qualidade e riscos antes de publicar.'], steps: [['Pesquisar', 'Transforme uma dúvida de mercado em perguntas úteis.'], ['Produzir', 'Crie um primeiro rascunho de campanha com IA.'], ['Validar', 'Revise dados, tom de voz e promessa antes de usar.']] },
  business: { eyebrow: 'MÓDULO 04 · EM BREVE', title: 'Negócios e Vendas', summary: 'Fundamentos de empreendedorismo, vendas e atendimento aplicados a negócios locais e digitais.', objectives: ['Fazer diagnóstico antes de oferecer uma solução.', 'Qualificar oportunidades e organizar um CRM simples.', 'Conduzir uma conversa com escuta, proposta e acompanhamento.'], steps: [['Diagnosticar', 'Entenda objetivo, desafio e contexto do cliente.'], ['Propor', 'Mostre como a solução reduz uma dor ou aproxima uma meta.'], ['Acompanhar', 'Registre o próximo passo e combine prazo.']] },
  production: { eyebrow: 'MÓDULO 05 · EM BREVE', title: 'Produção Digital', summary: 'Foto, vídeo, áudio e conteúdo para transformar uma ideia em uma comunicação que se vê, entende e compartilha.', objectives: ['Planejar uma pauta e uma narrativa curta.', 'Produzir conteúdo pensando em formato e objetivo.', 'Avaliar qualidade visual, sonora e de mensagem.'], steps: [['Planejar', 'Defina objetivo, público e chamada principal.'], ['Produzir', 'Capte e edite respeitando a identidade da marca.'], ['Publicar', 'Acompanhe o resultado e registre aprendizados.']] }
};

function showPage(page) { const target = document.getElementById(page); if (!target) return; views.forEach(view => view.classList.toggle('active-view', view === target)); menuItems.forEach(item => item.classList.toggle('active', item.dataset.page === page)); title.textContent = pageNames[page]; sidebar.classList.remove('open'); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function notify(message) { toast.textContent = message; toast.classList.add('show'); window.clearTimeout(notify.timer); notify.timer = window.setTimeout(() => toast.classList.remove('show'), 3200); }
function openModal(content) { modalContent.innerHTML = content; modal.classList.add('open'); modal.setAttribute('aria-hidden', 'false'); document.body.style.overflow = 'hidden'; }
function closeModal() { modal.classList.remove('open'); modal.setAttribute('aria-hidden', 'true'); document.body.style.overflow = ''; }

function courseModal(item, completed = false) {
  const objectives = item.objectives.map(text => `<li>${text}</li>`).join('');
  const steps = item.steps.map((step, index) => `<div class="content-step"><b>0${index + 1}</b><div><strong>${step[0]}</strong><span>${step[1]}</span></div></div>`).join('');
  openModal(`<p class="modal-overline">${item.eyebrow}</p><h2 class="modal-title" id="modal-title">${item.title}</h2><p class="modal-summary">${item.summary}</p><div class="modal-section"><h3>Ao final desta aula, você consegue</h3><ul>${objectives}</ul></div><div class="modal-section"><h3>Mapa da aula</h3><div class="content-steps">${steps}</div></div><div class="modal-section"><h3>Prática sugerida</h3><p class="modal-summary">Escolha uma empresa e descreva como ela atrai, orienta e convida uma pessoa a agir. Registre o que está claro e o que ainda gera dúvida.</p></div><div class="modal-action-row"><button class="outline-button" data-close-modal>Voltar</button><button class="solid-button" data-complete-lesson>${completed ? 'Aula concluída ✓' : 'Concluir aula'} <span>→</span></button></div>`);
}

function challengeModal(type) {
  const challenges = {
    campaign: { eyebrow: 'LABORATÓRIO · TRÁFEGO PAGO', title: 'Campanha de performance', summary: 'A Casa Verde é uma loja local de plantas e jardinagem. Com R$ 1.000 de orçamento simulado, construa uma primeira hipótese de campanha.', note: 'Não existe resposta única. O importante é ligar objetivo, público, criativo e métrica.' },
    content: { eyebrow: 'LABORATÓRIO · SOCIAL MEDIA', title: 'Conteúdo que conecta', summary: 'Crie uma sequência de conteúdo para uma pequena empresa. Pense no que faz uma pessoa parar, entender e conversar com a marca.', note: 'Conteúdo bom começa com uma observação útil, não com uma postagem genérica.' },
    proposal: { eyebrow: 'LABORATÓRIO · VENDAS', title: 'Apresente sua proposta', summary: 'Treine uma conversa de descoberta para transformar uma necessidade em proposta clara e honesta.', note: 'Uma boa proposta mostra que você entendeu o contexto antes de falar da solução.' },
    data: { eyebrow: 'LABORATÓRIO · DADOS', title: 'Leitura de campanha', summary: 'Uma campanha investiu R$ 1.000, alcançou 32 mil pessoas, trouxe 480 cliques e gerou 24 conversas. O que você investigaria primeiro?', note: 'Dados ajudam a construir a próxima hipótese, não apenas aprovar ou reprovar uma campanha.' }
  };
  const challenge = challenges[type];
  const details = type === 'campaign' ? `<div class="form-grid"><div class="field"><label for="objective">Objetivo principal</label><select id="objective"><option>Gerar conversas no WhatsApp</option><option>Levar pessoas à loja</option><option>Vender um produto</option></select></div><div class="field"><label for="audience">Público inicial</label><input id="audience" placeholder="Ex.: moradores próximos à loja" /></div></div>` : '';
  openModal(`<p class="modal-overline">${challenge.eyebrow}</p><h2 class="modal-title" id="modal-title">${challenge.title}</h2><p class="modal-summary">${challenge.summary}</p><form class="modal-form" id="challenge-form">${details}<div class="field"><label for="idea">Seu raciocínio</label><textarea id="idea" placeholder="Registre a primeira hipótese e o que você faria."></textarea></div><p class="modal-note">${challenge.note}</p><div class="modal-action-row"><button type="button" class="outline-button" data-close-modal>Salvar para depois</button><button type="submit" class="solid-button">Enviar desafio <span>→</span></button></div></form>`);
}

function notificationModal() { openModal(`<p class="modal-overline">ATUALIZAÇÕES</p><h2 class="modal-title" id="modal-title">Notificações</h2><div class="notification-list"><div class="notification"><i></i><div><b>Desafio disponível</b><span>O laboratório de campanha de performance está pronto para você.</span></div></div><div class="notification"><i></i><div><b>Briefing confirmado</b><span>Casa Verde · quinta-feira, 19h00.</span></div></div><div class="notification"><i></i><div><b>Você manteve sua consistência</b><span>São 6 dias seguidos de aprendizado na Formação SkS.</span></div></div></div><div class="modal-action-row"><button class="solid-button" data-close-modal>Entendi</button></div>`); }
function profileModal() { openModal(`<p class="modal-overline">PERFIL DO ALUNO</p><h2 class="modal-title" id="modal-title">Sua jornada SkS</h2><div class="profile-modal"><div class="avatar big">AM</div><div><strong>Alex Martins</strong><span>Turma Piloto 01 · Escola Técnica</span></div></div><div class="modal-section"><h3>Seu momento</h3><div class="content-steps"><div class="content-step"><b>18</b><div><strong>Aulas concluídas</strong><span>Você completou 62% da Base Comum.</span></div></div><div class="content-step"><b>05</b><div><strong>Desafios realizados</strong><span>Seu mapa de competências já está ganhando forma.</span></div></div></div></div><div class="modal-action-row"><button class="outline-button" data-close-modal>Fechar</button><button class="solid-button" data-go-page="desempenho">Ver desempenho <span>→</span></button></div>`); }
function helpModal() { openModal(`<p class="modal-overline">CENTRAL DE AJUDA</p><h2 class="modal-title" id="modal-title">Como podemos ajudar?</h2><p class="modal-summary">Esta versão do portal já contém as principais jornadas. Escolha uma opção para saber onde continuar.</p><div class="modal-section"><div class="content-steps"><div class="content-step"><b>01</b><div><strong>Continuar uma aula</strong><span>Acesse Minha formação e escolha o módulo em andamento.</span></div></div><div class="content-step"><b>02</b><div><strong>Fazer um desafio</strong><span>Abra o Laboratório para experimentar marketing, vendas ou dados.</span></div></div><div class="content-step"><b>03</b><div><strong>Ver sua evolução</strong><span>Consulte o Mapa de competências em Meu desempenho.</span></div></div></div></div><div class="modal-action-row"><button class="solid-button" data-close-modal>Entendi</button></div>`); }
function communityModal() { openModal(`<p class="modal-overline">TURMA PILOTO 01</p><h2 class="modal-title" id="modal-title">Comunidade SkS</h2><p class="modal-summary">Troque ideias, peça feedback e encontre pessoas para construir projetos em conjunto.</p><div class="community-feed" id="community-feed"><div class="feed-message"><b>Marina L. · há 20 min</b><p>Alguém quer trocar feedback sobre a campanha da Casa Verde?</p></div><div class="feed-message"><b>João S. · ontem</b><p>Compartilhei três referências de anúncios no mural da turma.</p></div></div><form class="modal-form" id="community-form"><div class="field"><label for="community-message">Sua mensagem</label><textarea id="community-message" placeholder="Escreva uma pergunta ou compartilhe uma ideia."></textarea></div><div class="modal-action-row"><button type="button" class="outline-button" data-close-modal>Fechar</button><button type="submit" class="solid-button">Publicar <span>→</span></button></div></form>`); }

menuItems.forEach(item => item.addEventListener('click', () => showPage(item.dataset.page)));
document.querySelectorAll('[data-page]').forEach(button => { if (!button.classList.contains('menu-item')) button.addEventListener('click', () => showPage(button.dataset.page)); });
document.querySelector('.mobile-menu').addEventListener('click', () => sidebar.classList.toggle('open'));
document.getElementById('continue-lesson').addEventListener('click', () => courseModal(courseContent.lesson));
document.getElementById('module-continue').addEventListener('click', () => courseModal(courseContent.lesson));
document.getElementById('start-challenge').addEventListener('click', () => challengeModal('campaign'));
document.getElementById('open-community').addEventListener('click', communityModal);
document.getElementById('notifications-button').addEventListener('click', notificationModal);
document.getElementById('profile-button').addEventListener('click', profileModal);
document.getElementById('profile-menu').addEventListener('click', profileModal);
document.getElementById('help-button').addEventListener('click', helpModal);
document.getElementById('confirm-event').addEventListener('click', event => { event.currentTarget.textContent = 'Presença confirmada ✓'; event.currentTarget.disabled = true; notify('Presença confirmada para o briefing com a Casa Verde.'); });
document.querySelectorAll('[data-challenge]').forEach(element => { const open = () => challengeModal(element.dataset.challenge); element.addEventListener('click', open); element.addEventListener('keydown', event => { if (event.key === 'Enter' || event.key === ' ') open(); }); });
document.querySelectorAll('[data-content]').forEach(element => { const open = () => courseModal(courseContent[element.dataset.content], element.dataset.content === 'communication'); element.addEventListener('click', open); element.addEventListener('keydown', event => { if (event.key === 'Enter' || event.key === ' ') open(); }); });
document.getElementById('modal-close').addEventListener('click', closeModal);
modal.addEventListener('click', event => { if (event.target === modal) closeModal(); });
document.addEventListener('keydown', event => { if (event.key === 'Escape') closeModal(); });
modalContent.addEventListener('click', event => { const button = event.target.closest('button'); if (!button) return; if (button.dataset.closeModal !== undefined) closeModal(); if (button.dataset.goPage) { closeModal(); showPage(button.dataset.goPage); } if (button.dataset.completeLesson !== undefined) { closeModal(); notify('Aula concluída! Seu progresso foi registrado.'); } });
modalContent.addEventListener('submit', event => { event.preventDefault(); if (event.target.id === 'challenge-form') { const idea = event.target.querySelector('#idea').value.trim(); if (!idea) { notify('Escreva seu raciocínio antes de enviar.'); return; } openModal(`<div class="success-card"><div class="success-mark">✓</div><h2>Desafio enviado!</h2><p>Seu raciocínio foi registrado. Ao receber feedback, ele será incorporado ao seu Mapa de Competências.</p><div class="modal-action-row"><button class="solid-button" data-close-modal>Voltar ao laboratório</button></div></div>`); } if (event.target.id === 'community-form') { const message = event.target.querySelector('#community-message').value.trim(); if (!message) { notify('Escreva uma mensagem para publicar.'); return; } modalContent.querySelector('#community-feed').insertAdjacentHTML('beforeend', `<div class="feed-message"><b>Alex Martins · agora</b><p>${message.replace(/[<>]/g, '')}</p></div>`); event.target.querySelector('#community-message').value = ''; notify('Mensagem publicada na comunidade.'); } });
